### ISSUE TITLE
Worker is stuck on malformed t.me url 

### ISSUE THREAD

**Issue by kotenok2000** [ArchiveTeam/telegram-grab#2]
10=302 https://t.me/... 
11=200 https://t.me/.../2?embed=1 
Server returned bad response. Sleeping.
Item post:Iranaseman:2434post:linkdoni_hamadan:56918post:PsnSeller_Best:14946post:azin_group:13271post:Pahkshfeshordh_shiraz:4759post:ptecompany:3258post:khazaeliena:5116post:anillparvaz:2387channel:...post:PositionExchange:686786post:bahramparchami:6334post:fanooscharter:1645post:LatinosPorPutin1:4post:Rasolmohammadiyan:1696post:SatoshiStreetBetsOriginal:1220461post:Asarab:5426post:dezedagen:584post:PoolClo2Miners:932316post:Fpn90:59955post:Cryptocom_PL:114874

**Comment by Arkiver2** [comment]
looks like item `channel:...` caused this

**Comment by Arkiver2** [comment]
Fixed with c057910681ffdd7d3d6e635cd832b95a4080aba7.
