### ISSUE TITLE
"Only public channels can be saved this way, and certain attachments (including PDFs and some very long videos) are not available."

### ISSUE THREAD

**Issue by F-36** [ArchiveTeam/telegram-grab#4]
https://wiki.archiveteam.org/index.php/Telegram

What is the size or length cut-off for videos? Are there any other attachments that aren't saved?

**Comment by Arkiver2** [comment]
This is related to https://github.com/ArchiveTeam/telegram-grab/issues/6 and the answer is the same. Will close this issue in favor for the other one.
